### ISSUE TITLE
Provide a button for instantly applying stored colors.

### ISSUE THREAD

**Issue by DDMoter** [EelisOtsamo/VertexColorTools#1]
Good afternoon! You have great plugin! For greater convenience, I suggest you add a button to quickly apply a stored color to the selected geometry. Something like that. Button under color will applies current color to the geometry with current plugin settings.
![изображение_2024-01-10_115449126](https://github.com/EelisOtsamo/VertexColorTools/assets/109672423/281bf56d-7a2d-4733-b65e-1336cd37c29f)

**Comment by DDMoter** [comment]
Good afternoon! You have great plugin! For greater convenience, I suggest you add a button to quickly apply a stored color to the selected geometry. Something like that. Button under color will applies current color to the geometry with current plugin settings.
![изображение_2024-01-10_115449126](https://github.com/EelisOtsamo/VertexColorTools/assets/109672423/281bf56d-7a2d-4733-b65e-1336cd37c29f)

**Comment by Safojas** [comment]
Will be great if colors also will have names like in Standart Palette addon  
![изображение](https://github.com/EelisOtsamo/VertexColorTools/assets/5460847/4c1e912a-a588-4819-8a96-bd984c722acb)

**Comment by EelisOtsamo** [comment]
These are both now implemented in the [1.1.0 release](https://github.com/EelisOtsamo/VertexColorTools/releases/tag/v1.1.0)
